# Generated by Django 2.1.7 on 2019-04-16 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190417_0339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-item__id', '-id']},
        ),
    ]
